# Generated by Django 3.2 on 2021-04-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas_app', '0002_task_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.CharField(choices=[('completed', 'Completed'), ('uncompleted', 'Uncompleted')], default='uncompleted', max_length=15, verbose_name='Status'),
        ),
    ]
